<script>
    const BASE_URL = "<?php echo BASE_URL; ?>"
</script>

<script src="<?php echo BASE_URL;?>Assets/js/helpers/sortable.min.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/data.filters.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/data.settings.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/data.locations.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/data.categories.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/data.chevrondown.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/data.autocomplete.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/data.keys.autocomplete.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/data.ads.js"></script>
<!-- <script src="<?php echo BASE_URL;?>Assets/js/data.articles.js"></script> -->
<script src="<?php echo BASE_URL;?>Assets/js/modal.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/toast.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/switch.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/checkbox-normal.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/modal-simple.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/app.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/search-filters.js"></script>
<!-- <script src="<?php echo BASE_URL;?>Assets/js/list-carousel.js"></script> -->
<script src="<?php echo BASE_URL;?>Assets/js/user-image-load.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/menu-user.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/form-edit.js"></script>
<!-- <script src="<?php echo BASE_URL;?>Assets/js/datepicker.js"></script> -->
<script src="<?php echo BASE_URL;?>Assets/js/table-list-show.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/create-direction.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/select-form.js"></script>
<!-- <script src="<?php echo BASE_URL;?>Assets/js/map-direction.js"></script> -->
<script src="<?php echo BASE_URL;?>Assets/js/actions-table-more.js"></script>
<!-- <script src="<?php echo BASE_URL;?>Assets/js/dropdown-table.js"></script> -->
<script src="<?php echo BASE_URL;?>Assets/js/ads-search.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/chevrondown.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/inputs-form.js"></script>
<!-- <script src="<?php echo BASE_URL;?>Assets/js/ads.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/movements.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/select-form-gloobal.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/order-by.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/my-pay.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/articles.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/file-drop-drag-upload.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/file-drop-drag-articles.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/file-drop-drag-articles-mini.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/surveys.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/ratioCv.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/cv.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/file-drop-drag-cv.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/tags.js"></script> -->
<script src="<?php echo BASE_URL;?>Assets/js/rangeGloobal.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/editors.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/select-edit.js"></script>
<!-- <script src="<?php echo BASE_URL;?>Assets/js/file-drop-drag-cv-imgs.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/file-drop-drag-video-cv.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/item-expand-more.js"></script> -->
<script src="<?php echo BASE_URL;?>Assets/js/date-select.js"></script>
<!-- <script src="<?php echo BASE_URL;?>Assets/js/file-drop-drag-logo.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/file-drop-drag-step4-cv.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/item-expand-more-step4.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/item-expand-more-step5.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/item-expand-more-step6.js"></script> -->
<!-- <script src="<?php echo BASE_URL;?>Assets/js/cv-validations.js"></script> -->
<script src="<?php echo BASE_URL;?>Assets/js/radio-wrapper.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/autocomplete.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/create-filters.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/subtabs.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/breadcumb.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/table-gloobal.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/table-gloobal-particulares.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/table-gloobal-categories.js"></script>
<script src="<?php echo BASE_URL;?>Assets/js/table-gloobal-locations.js"></script>
</body>
</html>
